#import "EAGLView.h"
#import "MainMode.h"
#import "OtamatoneCore.h"
#import <CoreMotion/CoreMotion.h>
#import <WebKit/WebKit.h>
#include <math.h>
@interface EAGLView()<UITableViewDelegate,UITableViewDataSource>@property(nonatomic,strong)MainMode*mainMode;@property(nonatomic,strong)CADisplayLink*animationTimer;@property(nonatomic,strong)CMMotionManager*motion;@property(nonatomic,strong)NSMutableDictionary<NSValue*,NSNumber*>*touchIDs;@property(nonatomic)int nextTouchID;@property(nonatomic,strong)UIView*overlay;@property(nonatomic,strong)UITableView*listTable;@property(nonatomic,strong)NSArray*listItems;@property(nonatomic)BOOL listIsMelody;@property(nonatomic,strong)WKWebView*webView;@property(nonatomic,strong)NSMutableDictionary<NSString*,UIImage*>*imageCache;@end
@implementation EAGLView
+(Class)layerClass{return CALayer.class;}
-(instancetype)initWithFrame:(CGRect)f{if((self=[super initWithFrame:f]))[self Initialize];return self;}-(instancetype)initWithCoder:(NSCoder*)c{if((self=[super initWithCoder:c]))[self Initialize];return self;}
-(void)Initialize{if(_mainMode)return;self.multipleTouchEnabled=YES;self.opaque=YES;self.backgroundColor=[UIColor colorWithRed:.07 green:.50 blue:.52 alpha:1];self.animationInterval=1.0/30;self.touchIDs=[NSMutableDictionary dictionary];self.nextTouchID=1;self.imageCache=[NSMutableDictionary dictionary];ACRInitialize();_mainMode=[MainMode new];_mainMode.view=self;[_mainMode Initialize];[self setupMotion];[self InitGUI];}
-(void)InitGUI{[self startAnimation];}-(MainMode*)GetMainMode{return self.mainMode;}
-(void)setupMotion{self.motion=[CMMotionManager new];self.motion.accelerometerUpdateInterval=1.0/60;if(self.motion.accelerometerAvailable){__weak typeof(self)w=self;[self.motion startAccelerometerUpdatesToQueue:NSOperationQueue.mainQueue withHandler:^(CMAccelerometerData*d,NSError*e){if(!d||e)return;ACRSetAcc((float)d.acceleration.x,(float)d.acceleration.y,(float)d.acceleration.z);[w setNeedsDisplay];}];}else NSLog(@"Otamatone64: accelerometer unavailable");}
-(void)setAnimationInterval:(NSTimeInterval)v{_animationInterval=MAX(1.0/120,v);if(self.animationTimer){[self stopAnimation];[self startAnimation];}}
-(void)startAnimation{if(self.animationTimer)return;self.animationTimer=[CADisplayLink displayLinkWithTarget:self selector:@selector(drawView)];self.animationTimer.preferredFramesPerSecond=30;[self.animationTimer addToRunLoop:NSRunLoop.mainRunLoop forMode:NSRunLoopCommonModes];}
-(void)stopAnimation{[self.animationTimer invalidate];self.animationTimer=nil;}-(void)drawView{[self.mainMode Update];[self.mainMode Render];[self setNeedsDisplay];}-(void)dealloc{[self stopAnimation];[self.motion stopAccelerometerUpdates];[self.mainMode Quit];}
-(UIImage*)img:(NSString*)n{UIImage*i=self.imageCache[n];if(!i){i=[UIImage imageNamed:n];if(i)self.imageCache[n]=i;}return i;}
-(CGRect)logicalViewport{CGFloat s=MIN(self.bounds.size.width/320.0,self.bounds.size.height/480.0),w=320*s,h=480*s;return CGRectMake((self.bounds.size.width-w)/2,(self.bounds.size.height-h)/2,w,h);}
-(CGPoint)logicalPoint:(CGPoint)p{CGRect v=[self logicalViewport];CGFloat s=v.size.width/320;return CGPointMake((p.x-v.origin.x)/s,(p.y-v.origin.y)/s);}
-(void)logical:(CGContextRef)c block:(void(^)(void))b{CGRect v=[self logicalViewport];CGFloat s=v.size.width/320;CGContextSaveGState(c);CGContextTranslateCTM(c,v.origin.x,v.origin.y);CGContextScaleCTM(c,s,s);CGContextClipToRect(c,CGRectMake(0,0,320,480));b();CGContextRestoreGState(c);}
-(void)drawImage:(UIImage*)im crop:(CGRect)cr dest:(CGRect)d{if(!im)return;CGImageRef cg=CGImageCreateWithImageInRect(im.CGImage,cr);if(!cg)return;[[UIImage imageWithCGImage:cg]drawInRect:d];CGImageRelease(cg);}
-(NSString*)skinSuffix{switch(SettingGetSkin()){case 1:return @"b";case 2:return @"red";case 3:return @"yellow";case 4:return @"blue";default:return @"w";}}
-(void)drawRect:(CGRect)r{CGContextRef c=UIGraphicsGetCurrentContext();[UIColor.blackColor setFill];CGContextFillRect(c,self.bounds);[self logical:c block:^{if(self.mainMode.mode==OtamaModeTitle)[self drawTitle];else[self drawGame];}];}
-(void)drawTitle{UIImage*bg=[self img:@"01_title_bg.png"];if(bg)[bg drawInRect:CGRectMake(0,0,320,480)];UIImage*cut=[self img:@"02_title_cutout.png"];if(cut)[self drawImage:cut crop:CGRectMake(0,0,MIN(320,cut.size.width),MIN(365,cut.size.height)) dest:CGRectMake(0,20,320,365)];[@"TAP TO START" drawAtPoint:CGPointMake(98,438) withAttributes:@{NSFontAttributeName:[UIFont boldSystemFontOfSize:16],NSForegroundColorAttributeName:UIColor.whiteColor}];}
-(void)drawGame{UIImage*bg=[self img:@"main_bg.png"];if(bg)for(CGFloat x=0;x<320;x+=bg.size.width)[bg drawInRect:CGRectMake(x,0,bg.size.width,480)];NSString*s=[self skinSuffix];UIImage*flag=[self img:[NSString stringWithFormat:@"otama_flag_%@.png",s]];if(flag){NSInteger f=MAX(0,MIN(7,self.mainMode.flagFrame));[self drawImage:flag crop:CGRectMake(0,f*115,400,115) dest:CGRectMake(-40,15,400,115)];}UIImage*body=[self img:[NSString stringWithFormat:@"otama_body_%@.png",s]];if(body)[self drawImage:body crop:CGRectMake(0,0,256,330) dest:CGRectMake(32,116,256,330)];UIImage*head=[self img:[NSString stringWithFormat:@"otama_head_%@.png",s]];if(head){CGFloat g=self.mainMode.mouth*34;[self drawImage:head crop:CGRectMake(20,5,280,142) dest:CGRectMake(20,218-g*.18,280,142)];[self drawImage:head crop:CGRectMake(20,145,280,140) dest:CGRectMake(20,326+g*.55,280,140)];NSInteger er=(self.mainMode.replaying||self.mainMode.recording)?1:0;CGRect e1=er?CGRectMake(332,105,36,35):CGRectMake(332,20,36,40),e2=er?CGRectMake(392,105,36,35):CGRectMake(392,20,36,40);[self drawImage:head crop:e1 dest:CGRectMake(113,260-g*.18,23,23)];[self drawImage:head crop:e2 dest:CGRectMake(185,260-g*.18,23,23)];}UIImage*menu=[self img:@"bot_menu_off.png"];if(menu)[menu drawInRect:CGRectMake(258,8,58,43)];if(!SettingState()->hideFukidashi&&self.mainMode.playing){UIImage*b=[self img:@"fukidashi_1.png"];if(b)[b drawInRect:CGRectMake(184,64,126,121)];[[NSString stringWithFormat:@"%.2fx",self.mainMode.pitch]drawAtPoint:CGPointMake(218,103) withAttributes:@{NSFontAttributeName:[UIFont boldSystemFontOfSize:14],NSForegroundColorAttributeName:UIColor.darkGrayColor}];}if(self.mainMode.recording)[@"REC" drawAtPoint:CGPointMake(8,8) withAttributes:@{NSFontAttributeName:[UIFont boldSystemFontOfSize:18],NSForegroundColorAttributeName:UIColor.redColor}];}
-(NSNumber*)touchID:(UITouch*)t create:(BOOL)c{NSValue*k=[NSValue valueWithNonretainedObject:t];NSNumber*n=self.touchIDs[k];if(!n&&c){n=@(self.nextTouchID++);self.touchIDs[k]=n;}return n;}
-(void)feed:(NSSet<UITouch*>*)ts phase:(int)ph{for(UITouch*t in ts){CGPoint p=[self logicalPoint:[t locationInView:self]];NSNumber*n=[self touchID:t create:ph==0];if(!n)continue;if(ph==0)ACRBegin(n.intValue,p.x,p.y);else if(ph==1)ACRMove(n.intValue,p.x,p.y);else{ACREnd(n.intValue,p.x,p.y);[self.touchIDs removeObjectForKey:[NSValue valueWithNonretainedObject:t]];}}[self updateInstrument];}
-(void)touchesBegan:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e{if(self.mainMode.mode==OtamaModeTitle){[self.mainMode SetMode:OtamaModeGame];return;}for(UITouch*x in t){CGPoint p=[self logicalPoint:[x locationInView:self]];if(p.x>=245&&p.y<=68){[self OpenMenu];return;}}[self feed:t phase:0];}
-(void)touchesMoved:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e{[self feed:t phase:1];}-(void)touchesEnded:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e{[self feed:t phase:2];}-(void)touchesCanceled:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e{[self feed:t phase:2];}
-(void)updateInstrument{const ACRCursor*pitch=NULL,*m[2]={0};int mc=0;for(int i=0;i<4;i++){const ACRCursor*c=ACRGetCursor(i);if(!c||!c->active||c->ended)continue;if(c->y>200&&mc<2)m[mc++]=c;if(c->x>=92&&c->x<=228&&c->y>=65&&c->y<=330)if(!pitch||c->y<pitch->y)pitch=c;}float mv=self.mainMode.mouth;if(mc>=2){float d=hypotf(m[0]->x-m[1]->x,m[0]->y-m[1]->y);mv=fmaxf(0,fminf(1,(d-18)/145));}else if(mc==1&&m[0]->y>300&&m[0]->x>=96&&m[0]->x<=223)mv=fmaxf(0,fminf(1,(m[0]->y-300)/145));if(pitch){float t=fmaxf(0,fminf(1,(330-pitch->y)/265)),semis=t*24-12,p=powf(2,semis/12);[self.mainMode userInputPitch:p mouth:mv active:YES];}else[self.mainMode userInputPitch:self.mainMode.pitch mouth:mv active:NO];}
-(UIViewController*)hostVC{UIResponder*r=self;while(r&&![r isKindOfClass:UIViewController.class])r=r.nextResponder;return(UIViewController*)r;}
-(void)removeOverlay{[self.overlay removeFromSuperview];self.overlay=nil;self.listTable=nil;[self.webView removeFromSuperview];self.webView=nil;}
-(void)OpenMenu{[self.mainMode userDidInteract];UIViewController*vc=[self hostVC];if(!vc)return;UIAlertController*a=[UIAlertController alertControllerWithTitle:@"OTAMATONE" message:nil preferredStyle:UIAlertControllerStyleActionSheet];__weak typeof(self)w=self;[a addAction:[UIAlertAction actionWithTitle:self.mainMode.recording?@"Stop recording":@"Record" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){if(w.mainMode.recording)[w promptSaveReplay:[w.mainMode stopRecording]];else[w.mainMode startRecording];}]];[a addAction:[UIAlertAction actionWithTitle:@"Playlist / Replays" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){[w showReplayList];}]];[a addAction:[UIAlertAction actionWithTitle:@"Melody" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){[w OpenMusicList2];}]];[a addAction:[UIAlertAction actionWithTitle:@"Settings" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){[w showSettings];}]];[a addAction:[UIAlertAction actionWithTitle:@"How To" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){[w OpenHowTo];}]];[a addAction:[UIAlertAction actionWithTitle:@"About" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){[w OpenAbout];}]];[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];a.popoverPresentationController.sourceView=self;a.popoverPresentationController.sourceRect=CGRectMake(self.bounds.size.width-30,30,1,1);[vc presentViewController:a animated:YES completion:nil];}
-(void)CloseMenu{}-(void)CloseMenuEnd{}-(void)CloseMenuToPlayList{[self showReplayList];}
-(void)promptSaveReplay:(OtamaReplay*)r{if(!r||!r.count)return;UIViewController*vc=[self hostVC];UIAlertController*a=[UIAlertController alertControllerWithTitle:@"Save recording" message:@"Name" preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField*t){t.text=@"My Otamatone";}];__weak typeof(self)w=self;[a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Save" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){NSError*er=nil;if(![w.mainMode saveRecording:r name:a.textFields.firstObject.text error:&er]&&er)[w showMessage:er.localizedDescription];}]];[vc presentViewController:a animated:YES completion:nil];}
-(void)OpenNameEntry{[self promptSaveReplay:[self.mainMode stopRecording]];}-(void)showMessage:(NSString*)m{UIViewController*vc=[self hostVC];UIAlertController*a=[UIAlertController alertControllerWithTitle:@"Otamatone" message:m preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];[vc presentViewController:a animated:YES completion:nil];}-(void)OpenAlert:(NSInteger)t{[self showMessage:[NSString stringWithFormat:@"Notice %ld",(long)t]];}-(void)InitAlert{}
-(void)showSettings{UIViewController*vc=[self hostVC];if(!vc)return;UIAlertController*a=[UIAlertController alertControllerWithTitle:@"Settings" message:@"Volume can be edited below; reopen to cycle other original options." preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField*t){t.placeholder=@"Volume 0-100";t.keyboardType=UIKeyboardTypeNumberPad;t.text=[NSString stringWithFormat:@"%d",(int)lrintf(SettingGetVolume()*100)];}];__weak typeof(self)w=self;[a addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Octave: %@",@[@"LOW",@"MID",@"HIGH"][SettingGetOctave()]] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){SettingSetOctave((SettingGetOctave()+1)%3);w.mainMode.audio.octave=SettingGetOctave();}]];[a addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Follow mode: %@",SettingIsFollow()?@"ON":@"OFF"] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){SettingSetFollow(!SettingIsFollow());}]];[a addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"FUKIDASHI Tuner: %@",SettingState()->hideFukidashi?@"OFF":@"ON"] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){SettingSetHideFukidashi(!SettingState()->hideFukidashi);}]];[a addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Skin: %@",@[@"WHITE",@"BLACK",@"PINK",@"YELLOW",@"BLUE"][SettingGetSkin()]] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){SettingSetSkin((SettingGetSkin()+1)%5);[w setNeedsDisplay];}]];[a addAction:[UIAlertAction actionWithTitle:@"Done" style:UIAlertActionStyleCancel handler:^(__unused UIAlertAction*x){SettingSetVolume(a.textFields.firstObject.text.floatValue/100);w.mainMode.audio.masterVolume=SettingGetVolume();}]];[vc presentViewController:a animated:YES completion:nil];}-(void)InitSettingView{[self showSettings];}
-(void)showReplayList{NSMutableArray*i=[NSMutableArray arrayWithObjects:@"Preset 1",@"Preset 2",nil];for(OtamaReplay*r in[self.mainMode availableUserReplays])[i addObject:r.name?:@"Recording"];self.listItems=i;self.listIsMelody=NO;[self showList:@"Playlist"];}
-(void)OpenMusicList{[self showReplayList];}-(void)OpenMusicList2{self.listItems=@[@"Kaeru no Uta",@"Greensleeves",@"Eine kleine Nachtmusik",@"Ooki na Furudokei",@"Kirakira Boshi",@"Shiawase nara Te wo Tatakou",@"French Folk Song",@"British Folk",@"Kiyoshi Kono Yoru",@"Symphony No. 9",@"Hotaru no Hikari"];self.listIsMelody=YES;[self showList:@"Melody"];}
-(void)showList:(NSString*)title{[self removeOverlay];CGRect v=[self logicalViewport];UIView*o=[[UIView alloc]initWithFrame:v];o.backgroundColor=[UIColor colorWithWhite:.97 alpha:.98];o.layer.cornerRadius=12;o.clipsToBounds=YES;self.overlay=o;[self addSubview:o];UILabel*l=[[UILabel alloc]initWithFrame:CGRectMake(12,4,o.bounds.size.width-24,40)];l.text=title;l.font=[UIFont boldSystemFontOfSize:22];l.textAlignment=NSTextAlignmentCenter;[o addSubview:l];UIButton*d=[UIButton buttonWithType:UIButtonTypeSystem];d.frame=CGRectMake(o.bounds.size.width-72,4,64,40);[d setTitle:@"Done" forState:UIControlStateNormal];[d addTarget:self action:@selector(removeOverlay) forControlEvents:UIControlEventTouchUpInside];[o addSubview:d];UITableView*t=[[UITableView alloc]initWithFrame:CGRectMake(0,44,o.bounds.size.width,o.bounds.size.height-44) style:UITableViewStylePlain];t.delegate=self;t.dataSource=self;self.listTable=t;[o addSubview:t];}
-(NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return self.listItems.count;}-(UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)ip{UITableViewCell*c=[t dequeueReusableCellWithIdentifier:@"c"];if(!c)c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"c"];c.textLabel.text=self.listItems[ip.row];c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return c;}-(void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)ip{[t deselectRowAtIndexPath:ip animated:YES];if(self.listIsMelody){[self.mainMode setMelodyIndexNative:ip.row];[self.mainMode SetModeNoFade:OtamaModeMelody];}else{if(ip.row<2)[self.mainMode ReplayPreset:ip.row];else[self.mainMode Replay:ip.row-2];[self.mainMode SetModeNoFade:OtamaModeGame];}[self removeOverlay];}
-(void)CloseMusicListToMenu{[self removeOverlay];[self OpenMenu];}-(void)CloseMusicListToMelody{[self removeOverlay];}
-(void)openHTML:(NSString*)base{[self removeOverlay];CGRect v=[self logicalViewport];UIView*o=[[UIView alloc]initWithFrame:v];o.backgroundColor=UIColor.whiteColor;self.overlay=o;[self addSubview:o];UIButton*d=[UIButton buttonWithType:UIButtonTypeSystem];d.frame=CGRectMake(o.bounds.size.width-70,0,66,42);[d setTitle:@"Done" forState:UIControlStateNormal];[d addTarget:self action:@selector(removeOverlay) forControlEvents:UIControlEventTouchUpInside];[o addSubview:d];WKWebView*w=[[WKWebView alloc]initWithFrame:CGRectMake(0,42,o.bounds.size.width,o.bounds.size.height-42)];self.webView=w;[o addSubview:w];BOOL jp=[NSLocale.preferredLanguages.firstObject hasPrefix:@"ja"];NSString*n=[NSString stringWithFormat:@"m_%@_%@",base,jp?@"jp":@"eng"];NSURL*u=[NSBundle.mainBundle URLForResource:n withExtension:@"html"];if(!u)u=[NSBundle.mainBundle URLForResource:[NSString stringWithFormat:@"%@_%@",base,jp?@"jp":@"eng"] withExtension:@"html"];if(u)[w loadFileURL:u allowingReadAccessToURL:NSBundle.mainBundle.bundleURL];}
-(void)OpenHowTo{[self openHTML:@"howto"];}-(void)OpenAbout{[self openHTML:@"about"];}-(void)StopMusic{[self.mainMode stopMelodyNative];}-(void)setMusic:(NSInteger)i{[self.mainMode setMelodyIndexNative:i];}
-(void)SetMusicIndex01{[self setMusic:0];}-(void)SetMusicIndex02{[self setMusic:1];}-(void)SetMusicIndex03{[self setMusic:2];}-(void)SetMusicIndex04{[self setMusic:3];}-(void)SetMusicIndex05{[self setMusic:4];}-(void)SetMusicIndex06{[self setMusic:5];}-(void)SetMusicIndex07{[self setMusic:6];}-(void)SetMusicIndex08{[self setMusic:7];}-(void)SetMusicIndex09{[self setMusic:8];}-(void)SetMusicIndex10{[self setMusic:9];}-(void)SetMusicIndex11{[self setMusic:10];}
@end
