#import "MainMode.h"
#import "OtamatoneCore.h"
#import <UIKit/UIKit.h>
#include <math.h>
@interface MainMode()@property(nonatomic,strong)OtamaAudio*audio;@property(nonatomic,strong)OtamaReplay*recordingObject;@property(nonatomic,strong)OtamaReplay*currentReplay;@property(nonatomic)NSInteger replayFrame;@property(nonatomic)NSInteger idleCounter;@property(nonatomic)NSInteger melodyIndex;@property(nonatomic)BOOL effectReplay;@end
@implementation MainMode
-(instancetype)init{if((self=[super init])){_mouth=.5f;_pitch=1;_melodyIndex=-1;}return self;}
-(void)Initialize{SettingInitialize();ACRInitialize();self.audio=[OtamaAudio new];self.audio.masterVolume=SettingGetVolume();self.audio.octave=SettingGetOctave();NSError*e=nil;if(![self.audio start:&e])NSLog(@"Otamatone64 audio: %@",e);[self LoadParam];[self PreloadPreset];self.idleCounter=0;self.flagFrame=0;self.headAngle=0;self.showHUD=YES;[self SetModeNoFade:OtamaModeTitle];}
-(void)Quit{[self.audio stop];[self.audio stopMelody];}
-(void)SetMode:(NSInteger)m{[self QuitMode];self.mode=(OtamaMainModeID)m;[self InitMode];}-(void)SetModeNoFade:(NSInteger)m{[self SetMode:m];}
-(void)InitMode{switch(self.mode){case OtamaModeTitle:[self InitTitle];break;case OtamaModeGame:[self InitGame];break;case OtamaModeMenu:[self InitMenu];break;case OtamaModeTutorial:[self InitTutorial];break;case OtamaModeSetting:[self InitSetting];break;case OtamaModeFileList:[self InitFileList];break;case OtamaModeReplay:[self InitReplay];break;case OtamaModeMelody:[self InitMelody];break;case OtamaModeDebug:[self InitDebug];break;}}
-(void)QuitMode{switch(self.mode){case OtamaModeTitle:[self QuitTitle];break;case OtamaModeGame:[self QuitGame];break;case OtamaModeMenu:[self QuitMenu];break;case OtamaModeTutorial:[self QuitTutorial];break;case OtamaModeSetting:[self QuitSetting];break;case OtamaModeFileList:[self QuitFileList];break;case OtamaModeReplay:[self QuitReplay];break;case OtamaModeMelody:[self QuitMelody];break;case OtamaModeDebug:[self QuitDebug];break;}}
-(void)Update{[self UpdateMode];}-(void)Render{[self RenderMode];}
-(void)UpdateMode{switch(self.mode){case OtamaModeTitle:[self UpdateTitle];break;case OtamaModeGame:[self UpdateGame];break;case OtamaModeMenu:[self UpdateMenu];break;case OtamaModeTutorial:[self UpdateTutorial];break;case OtamaModeSetting:[self UpdateSetting];break;case OtamaModeFileList:[self UpdateFileList];break;case OtamaModeReplay:[self UpdateReplay];break;case OtamaModeMelody:[self UpdateMelody];break;case OtamaModeDebug:[self UpdateDebug];break;}}
-(void)RenderMode{switch(self.mode){case OtamaModeTitle:[self RenderTitle];break;case OtamaModeGame:[self RenderGame];break;case OtamaModeMenu:[self RenderMenu];break;case OtamaModeTutorial:[self RenderTutorial];break;case OtamaModeSetting:[self RenderSetting];break;case OtamaModeFileList:[self RenderFileList];break;case OtamaModeReplay:[self RenderReplay];break;case OtamaModeMelody:[self RenderMelody];break;case OtamaModeDebug:[self RenderDebug];break;}}
-(void)InitTitle{[self.audio playUISoundNamed:@"title01"];self.playing=NO;}-(void)UpdateTitle{}-(void)RenderTitle{}-(void)QuitTitle{}
-(void)InitGame{self.idleCounter=0;self.playing=NO;self.audio.masterVolume=SettingGetVolume();self.audio.octave=SettingGetOctave();}
-(void)UpdateGame{float y=ACRGetAccY(),z=ACRGetAccZ();self.headAngle=atan2f(-z,-y);float ph=(self.headAngle+(float)M_PI)/(2*(float)M_PI);NSInteger f=(NSInteger)floorf(ph*8);self.flagFrame=((f%8)+8)%8;if(self.currentReplay){[self UpdateReplay];return;}if(self.recording){[self.recordingObject appendPitch:self.playing?self.pitch:-1 mouth:self.playing?self.mouth:-1];if(self.recordingObject.count>=8999)self.recording=NO;}if(!self.playing&&!self.recording&&!self.currentReplay){if(++self.idleCounter>=1800){self.idleCounter=0;NSInteger i=1+arc4random_uniform(14);if(i==4)i=5;OtamaReplay*e=[OtamaReplay replayWithBundleName:[NSString stringWithFormat:@"Effect%02ld.otama",(long)i]];if(e){self.effectReplay=YES;[self playReplayObject:e];}}}ACRUpdate();}
-(void)RenderGame{}-(void)QuitGame{[self.audio setPitch:self.pitch mouth:self.mouth active:NO];}
-(void)InitMenu{}-(void)UpdateMenu{}-(void)RenderMenu{}-(void)QuitMenu{}-(void)InitTutorial{}-(void)UpdateTutorial{}-(void)RenderTutorial{}-(void)QuitTutorial{}-(void)InitSetting{}-(void)UpdateSetting{}-(void)RenderSetting{}-(void)QuitSetting{[self SaveParam];}-(void)InitFileList{}-(void)UpdateFileList{}-(void)RenderFileList{}-(void)QuitFileList{}-(void)InitFileList2{}-(void)UpdateFileList2{}-(void)RenderFileList2{}-(void)QuitFileList2{}-(void)InitDebug{}-(void)UpdateDebug{}-(void)RenderDebug{}-(void)QuitDebug{}
-(void)InitReplay{self.replayFrame=0;}-(void)UpdateReplay{if(!self.currentReplay)return;if(self.replayFrame>=self.currentReplay.count){[self stopReplay];return;}OtamaReplayFrame f=self.currentReplay.frames[self.replayFrame++];BOOL on=f.pitch>=0&&f.mouth>=0;if(on){self.pitch=f.pitch;self.mouth=f.mouth;}self.playing=on;[self.audio setPitch:self.pitch mouth:self.mouth active:on];}-(void)RenderReplay{}-(void)QuitReplay{[self stopReplay];}
-(void)InitMelody{if(self.melodyIndex<0)self.melodyIndex=0;[self.audio playMelodyIndex:self.melodyIndex];}-(void)UpdateMelody{[self UpdateGame];}-(void)RenderMelody{}-(void)QuitMelody{[self.audio stopMelody];}
-(void)SaveParam{SettingSave();}-(void)LoadParam{self.audio.masterVolume=SettingGetVolume();self.audio.octave=SettingGetOctave();}-(void)PreloadPreset{(void)[OtamaReplay replayWithBundleName:@"Preset1.otama"];(void)[OtamaReplay replayWithBundleName:@"Preset2.otama"];}
-(void)ChangeSkin{}-(void)UpdateSkin{}-(void)DeleteSkin{}-(void)ShowHUD{self.showHUD=YES;}-(void)RequestHUD{self.showHUD=!self.showHUD;}
-(NSArray<OtamaReplay*>*)availableUserReplays{NSMutableArray*out=[NSMutableArray array];for(NSURL*u in OtamaUserReplayURLs()){OtamaReplay*r=[OtamaReplay replayWithURL:u error:nil];if(r)[out addObject:r];}return out;}
-(void)Replay:(NSInteger)i{NSArray*a=[self availableUserReplays];if(i>=0&&i<a.count)[self playReplayObject:a[i]];}-(void)ReplayPreset:(NSInteger)i{OtamaReplay*r=[OtamaReplay replayWithBundleName:[NSString stringWithFormat:@"Preset%ld.otama",(long)i+1]];if(r)[self playReplayObject:r];}-(void)DeleteReplay:(NSInteger)i{NSArray*u=OtamaUserReplayURLs();if(i>=0&&i<u.count)[NSFileManager.defaultManager removeItemAtURL:u[i] error:nil];}-(BOOL)ReplayDataSkinCheck{return self.currentReplay?(self.currentReplay.skin>=0&&self.currentReplay.skin<=4):YES;}
-(void)playReplayObject:(OtamaReplay*)r{[self userDidInteract];self.currentReplay=r;self.replayFrame=0;if(r.skin>=0&&r.skin<=4)SettingSetSkin(r.skin);if(r.octave>=0&&r.octave<=2)SettingSetOctave(r.octave);self.audio.octave=SettingGetOctave();}
-(void)stopReplay{self.currentReplay=nil;self.replayFrame=0;self.effectReplay=NO;self.playing=NO;[self.audio setPitch:self.pitch mouth:self.mouth active:NO];}-(BOOL)replaying{return self.currentReplay!=nil;}-(NSInteger)replayCount{return(NSInteger)self.currentReplay.count;}
-(void)userInputPitch:(float)p mouth:(float)m active:(BOOL)a{if(a&&self.currentReplay&&self.effectReplay)[self stopReplay];[self userDidInteract];self.pitch=p;self.mouth=fmaxf(0,fminf(1,m));self.playing=a;self.audio.masterVolume=SettingGetVolume();self.audio.octave=SettingGetOctave();[self.audio setPitch:p mouth:self.mouth active:a];}
-(void)userDidInteract{self.idleCounter=0;}-(void)startRecording{if(self.currentReplay)[self stopReplay];self.recordingObject=[OtamaReplay newRecordingWithName:@"Recording" skin:SettingGetSkin() octave:SettingGetOctave()];self.recording=YES;self.idleCounter=0;}-(OtamaReplay*)stopRecording{self.recording=NO;OtamaReplay*r=self.recordingObject;self.recordingObject=nil;return r;}
-(BOOL)saveRecording:(OtamaReplay*)r name:(NSString*)name error:(NSError**)error{if(!r)return NO;r.name=name.length?name:@"Recording";NSArray*urls=OtamaUserReplayURLs();NSInteger slot=1;NSMutableSet*used=[NSMutableSet set];for(NSURL*u in urls)[used addObject:u.lastPathComponent];while(slot<=10&&[used containsObject:[NSString stringWithFormat:@"Record%02ld.otama",(long)slot]])slot++;if(slot>10){if(error)*error=[NSError errorWithDomain:@"Otamatone64" code:10 userInfo:@{NSLocalizedDescriptionKey:@"The original 10 recording slots are full."}];return NO;}NSURL*u=[OtamaRecordingsDirectory()URLByAppendingPathComponent:[NSString stringWithFormat:@"Record%02ld.otama",(long)slot]];return[r writeToURL:u error:error];}
-(void)setMelodyIndexNative:(NSInteger)i{self.melodyIndex=MAX(0,MIN(10,i));[self.audio stopMelody];[self.audio playMelodyIndex:self.melodyIndex];}-(void)stopMelodyNative{[self.audio stopMelody];self.melodyIndex=-1;}
@end
