#import "OtamaAudio.h"
@interface OtamaAudio()<AVAudioPlayerDelegate>@property(nonatomic,strong)AVAudioEngine*engine;@property(nonatomic,strong)NSMutableArray<AVAudioPlayerNode*>*nodes;@property(nonatomic,strong)NSMutableArray<AVAudioUnitVarispeed*>*rates;@property(nonatomic,strong)NSMutableArray<AVAudioPCMBuffer*>*buffers;@property(nonatomic,strong)AVAudioPlayer*melodyPlayer;@property(nonatomic,strong)AVAudioPlayer*uiPlayer;@property(nonatomic)BOOL instrumentActive;@end
@implementation OtamaAudio
-(instancetype)init{if((self=[super init])){_masterVolume=.82f;_octave=1;}return self;}
-(AVAudioPCMBuffer*)bufferFor:(NSString*)base error:(NSError**)error{NSURL*u=[[NSBundle mainBundle]URLForResource:base withExtension:@"wav"];if(!u)return nil;AVAudioFile*f=[[AVAudioFile alloc]initForReading:u error:error];if(!f)return nil;AVAudioPCMBuffer*b=[[AVAudioPCMBuffer alloc]initWithPCMFormat:f.processingFormat frameCapacity:(AVAudioFrameCount)f.length];return[f readIntoBuffer:b error:error]?b:nil;}
-(BOOL)start:(NSError**)error{if(self.engine.running)return YES;AVAudioSession*s=AVAudioSession.sharedInstance;[s setCategory:AVAudioSessionCategoryPlayback mode:AVAudioSessionModeDefault options:AVAudioSessionCategoryOptionMixWithOthers error:nil];[s setActive:YES error:nil];self.engine=[AVAudioEngine new];self.nodes=[NSMutableArray array];self.rates=[NSMutableArray array];self.buffers=[NSMutableArray array];for(NSString*n in @[@"open_low",@"close_low",@"open_mid",@"close_mid",@"open_high",@"close_high"]){AVAudioPCMBuffer*b=[self bufferFor:n error:error];if(!b)return NO;AVAudioPlayerNode*node=[AVAudioPlayerNode new];AVAudioUnitVarispeed*rate=[AVAudioUnitVarispeed new];[self.engine attachNode:node];[self.engine attachNode:rate];[self.engine connect:node to:rate format:b.format];[self.engine connect:rate to:self.engine.mainMixerNode format:nil];node.volume=0;rate.rate=1;[node scheduleBuffer:b atTime:nil options:AVAudioPlayerNodeBufferLoops completionHandler:nil];[self.nodes addObject:node];[self.rates addObject:rate];[self.buffers addObject:b];}if(![self.engine startAndReturnError:error])return NO;for(AVAudioPlayerNode*n in self.nodes)[n play];return YES;}
-(void)stop{for(AVAudioPlayerNode*n in self.nodes)n.volume=0;[self.engine stop];self.instrumentActive=NO;}
-(void)setPitch:(float)pitch mouth:(float)mouth active:(BOOL)active{mouth=fmaxf(0,fminf(1,mouth));pitch=fmaxf(.125f,fminf(8,pitch));int bank=MAX(0,MIN(2,self.octave));for(int i=0;i<3;i++){int oi=i*2,ci=oi+1;float v=(active&&i==bank)?self.masterVolume:0;self.nodes[oi].volume=v*mouth;self.nodes[ci].volume=v*(1-mouth);self.rates[oi].rate=pitch;self.rates[ci].rate=pitch;}self.instrumentActive=active;}
-(void)playMelodyIndex:(NSInteger)i{NSArray*n=@[@"s1_kae",@"s2_gre",@"s3_ein",@"s4_ook",@"s5_kir",@"s6_shi",@"s7_fur",@"s8_bri",@"s9_kiy",@"s10_sym",@"s11_hot4"];if(i<0||i>=n.count)return;NSURL*u=[[NSBundle mainBundle]URLForResource:n[i] withExtension:@"wav"];if(!u)return;self.melodyPlayer=[[AVAudioPlayer alloc]initWithContentsOfURL:u error:nil];self.melodyPlayer.volume=.85;[self.melodyPlayer prepareToPlay];[self.melodyPlayer play];}
-(void)stopMelody{[self.melodyPlayer stop];self.melodyPlayer=nil;}
-(void)playUISoundNamed:(NSString*)name{NSURL*u=[[NSBundle mainBundle]URLForResource:name withExtension:@"wav"];if(!u)return;self.uiPlayer=[[AVAudioPlayer alloc]initWithContentsOfURL:u error:nil];[self.uiPlayer play];}
@end
