#import "OtamaReplay.h"
static const NSUInteger H=0x120,N=0x80,SO=0x80,OO=0x84,CO=0x88,MAXF=8999;
@interface OtamaReplay()@property(nonatomic,strong)NSMutableData*frameData;@property(nonatomic,strong)NSData*originalHeader;@end
@implementation OtamaReplay
-(NSUInteger)count{return self.frameData.length/sizeof(OtamaReplayFrame);}-(const OtamaReplayFrame*)frames{return(const OtamaReplayFrame*)self.frameData.bytes;}
+(instancetype)newRecordingWithName:(NSString*)name skin:(int)skin octave:(int)octave{OtamaReplay*r=[OtamaReplay new];r.name=name.length?name:@"Recording";r.skin=skin;r.octave=octave;r.frameData=[NSMutableData data];r.originalHeader=[NSData dataWithLength:H];return r;}
+(instancetype)replayWithBundleName:(NSString*)name{NSString*base=[name stringByDeletingPathExtension],*ext=name.pathExtension.length?name.pathExtension:@"otama";NSURL*u=[[NSBundle mainBundle]URLForResource:base withExtension:ext];return u?[self replayWithURL:u error:nil]:nil;}
+(instancetype)replayWithURL:(NSURL*)url error:(NSError**)error{NSData*d=[NSData dataWithContentsOfURL:url options:0 error:error];if(!d||d.length<H)return nil;const uint8_t*p=d.bytes;uint32_t count=0;memcpy(&count,p+CO,4);if(H+(NSUInteger)count*sizeof(OtamaReplayFrame)>d.length)return nil;OtamaReplay*r=[OtamaReplay new];const void*nul=memchr(p,0,N);NSUInteger nl=nul?(NSUInteger)((const uint8_t*)nul-p):N;r.name=[[NSString alloc]initWithBytes:p length:nl encoding:NSUTF8StringEncoding]?:url.lastPathComponent.stringByDeletingPathExtension;int32_t s=0,o=1;memcpy(&s,p+SO,4);memcpy(&o,p+OO,4);r.skin=s;r.octave=o;r.originalHeader=[d subdataWithRange:NSMakeRange(0,H)];r.frameData=[[d subdataWithRange:NSMakeRange(H,(NSUInteger)count*sizeof(OtamaReplayFrame))]mutableCopy];return r;}
-(void)appendPitch:(float)pitch mouth:(float)mouth{if(self.count>=MAXF)return;OtamaReplayFrame f={pitch,mouth};[self.frameData appendBytes:&f length:sizeof(f)];}
-(BOOL)writeToURL:(NSURL*)url error:(NSError**)error{NSMutableData*h=[(self.originalHeader?:[NSData dataWithLength:H])mutableCopy];if(h.length<H)[h setLength:H];memset(h.mutableBytes,0,N);NSData*n=[self.name dataUsingEncoding:NSUTF8StringEncoding]?:[NSData data];NSUInteger nl=MIN(n.length,N-1);memcpy(h.mutableBytes,n.bytes,nl);int32_t s=self.skin,o=self.octave;uint32_t c=(uint32_t)self.count;memcpy((uint8_t*)h.mutableBytes+SO,&s,4);memcpy((uint8_t*)h.mutableBytes+OO,&o,4);memcpy((uint8_t*)h.mutableBytes+CO,&c,4);NSMutableData*out=[h mutableCopy];[out appendData:self.frameData];return[out writeToURL:url options:NSDataWritingAtomic error:error];}
@end
NSURL*OtamaRecordingsDirectory(void){NSURL*docs=[[[NSFileManager defaultManager]URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask]firstObject];NSURL*dir=[docs URLByAppendingPathComponent:@"Otamatone" isDirectory:YES];[[NSFileManager defaultManager]createDirectoryAtURL:dir withIntermediateDirectories:YES attributes:nil error:nil];return dir;}
NSArray<NSURL*>*OtamaUserReplayURLs(void){NSArray*a=[[NSFileManager defaultManager]contentsOfDirectoryAtURL:OtamaRecordingsDirectory() includingPropertiesForKeys:nil options:NSDirectoryEnumerationSkipsHiddenFiles error:nil]?:@[];NSPredicate*p=[NSPredicate predicateWithBlock:^BOOL(NSURL*u,NSDictionary*_){return[u.pathExtension.lowercaseString isEqualToString:@"otama"];}];return[[a filteredArrayUsingPredicate:p]sortedArrayUsingComparator:^NSComparisonResult(NSURL*a,NSURL*b){return[a.lastPathComponent localizedCaseInsensitiveCompare:b.lastPathComponent];}];}
